# Generated by Django 4.2.2 on 2023-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_delete_user_college_institute_alter_college_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='closing_rank',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='opening_rank',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='round',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='seat_type',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='year',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
